const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const { join } = require('node:path')

const root = join(__dirname, '..')
const html = readFileSync(join(root, 'src/renderer/index.html'), 'utf8')
const renderer = readFileSync(join(root, 'src/renderer/renderer.js'), 'utf8')
const style = readFileSync(join(root, 'src/renderer/style.css'), 'utf8')
const main = readFileSync(join(root, 'src/main.ts'), 'utf8')
const preload = readFileSync(join(root, 'src/preload.ts'), 'utf8')
const agentManager = readFileSync(join(root, 'src/powerpoint/PowerPointAgentManager.ts'), 'utf8')

assert.match(html, /PowerPoint Bridge/)
assert.match(html, /bridge-journey/)
assert.match(html, /data-step="agent"/)
assert.match(html, /data-step="powerpoint"/)
assert.match(html, /data-step="media"/)
assert.match(html, /bridge-live-card/)
assert.match(html, /bridge-preview-image/)
assert.match(html, /bridge-recovery-card/)
assert.match(html, /Advanced Diagnostics/)
assert.match(html, /Modern \.NET Agent/)
assert.match(html, /Legacy PowerShell/)
assert.match(html, /Compatibility mode lebih lambat/)

assert.match(renderer, /updateBridgeStatusCenter/)
assert.match(renderer, /setBridgeStep/)
assert.match(renderer, /refreshPresentationDiagnostics/)
assert.match(renderer, /previewDataUrl/)
assert.match(renderer, /Microsoft Office 32-bit terdeteksi/)

assert.match(style, /\.bridge-hero--status/)
assert.match(style, /\.bridge-step/)
assert.match(style, /\.bridge-live-card/)
assert.match(style, /\.bridge-live-card__image/)
assert.match(style, /\.bridge-recovery-card/)
assert.match(style, /\.bridge-diagnostics/)

assert.match(main, /presentation-bridge:diagnostics/)
assert.match(main, /getPresentationDiagnostics/)
assert.match(preload, /getPresentationDiagnostics/)

assert.match(agentManager, /SION_PRESENTATION_AGENT_PATH/)
assert.match(agentManager, /process\.resourcesPath/)
assert.match(agentManager, /process\.cwd\(\)/)
assert.match(agentManager, /npm run agent:publish/)

console.log('SION Link bridge UI contract: 32 assertions passed')
